### ISSUE TITLE
Check status of your BACKEND_HOST endpoint in conf/sarjitsu.conf

### ISSUE THREAD

**Issue by lubry** [arcolife/sarjitsu#10]
I am install using this method [(https://github.com/distributed-system-analysis/sarjitsu)](https://github.com/distributed-system-analysis/sarjitsu) when i import sa binari file i get message. 
`(venv) root@user:/var/lib/docker/aufs/diff/213e4558e4b3509129f7071275353c916c1dd97de2707b600363156716686125/home/sarjitsu/sarjitsu-2.0# ./vizit -f /var/log/sa/sa01 `
`[07/31/17 16:52:25 WIB] - Single file mode selected..`
`[07/31/17 16:52:25 WIB] - attempting to upload file(s) to :80/upload/ now..`
`[07/31/17 16:52:25 WIB] - Current connection TIMEOUT value: 10 seconds..`
`Usage: ping [-aAbBdDfhLnOqrRUvV] [-c count] [-i interval] [-I interface]
            [-m mark] [-M pmtudisc_option] [-l preload] [-p pattern] [-Q tos]
            [-s packetsize] [-S sndbuf] [-t ttl] [-T timestamp_option]
            [-w deadline] [-W timeout] [hop1 ...] destination`
`[07/31/17 16:52:38 WIB] - :80/upload/ is down.`
`[07/31/17 16:52:38 WIB] - Check status of your BACKEND_HOST endpoint in conf/sarjitsu.conf`

Docker logs

> `time="2017-07-31T16:43:18.110862685+07:00" level=error msg="Error getting nodes: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again." 

> time="2017-07-31T16:43:18.110902075+07:00" level=error msg="Handler for GET /v1.30/nodes returned error: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again." 

> time="2017-07-31T16:43:18.136831551+07:00" level=error msg="Handler for GET /v1.30/secrets returned error: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again." 

> time="2017-07-31T16:43:18.149960372+07:00" level=error msg="Error getting services: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again." 

> time="2017-07-31T16:43:18.150002083+07:00" level=error msg="Handler for GET /v1.30/services returned error: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again." 

> time="2017-07-31T16:43:21.060967540+07:00" level=error msg="Error getting nodes: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again." 

> time="2017-07-31T16:43:21.061046117+07:00" level=error msg="Handler for GET /v1.30/nodes returned error: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again." 

> time="2017-07-31T16:43:21.115897259+07:00" level=error msg="Handler for GET /v1.30/secrets returned error: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again." 

> time="2017-07-31T16:43:21.138770516+07:00" level=error msg="Error getting services: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again." 

> time="2017-07-31T16:43:21.138824555+07:00" level=error msg="Handler for GET /v1.30/services returned error: This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again." `
> 

What the mean this message? but i have no problem when upload using Sarjitsu v.2.0 Web.

Thanks.

**Comment by arcolife** [comment]
yeah I pushed updates to web app, but didn't update vizit yet. 
Also, about:
```
time="2017-07-31T16:43:21.138824555+07:00" level=error msg="Handler for GET /v1.30/services returned error: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again." `
```

I don't know. I don't use docker swarm in this project. Are you deploying though swarm? I've never used it.
Sarjitsu supports either docker-compose or openshift deployment.

**Comment by lubry** [comment]
No i am not using docker swarm. I am using `docker-compose`
i has mounting IP manualy to backend host

```
BACKEND_HOST=172.19.0.2
BACKEND_SERVER_PORT=8000
```

```
sarjitsu-2.0# ./vizit -f /var/log/sa/sa04 
[08/01/17 14:30:06 WIB] - Single file mode selected..
[08/01/17 14:30:06 WIB] - attempting to upload file(s) to 172.19.0.3:8001/upload/ now..
[08/01/17 14:30:06 WIB] - Current connection TIMEOUT value: 10 seconds..
[08/01/17 14:30:09 WIB] - 172.19.0.3:8001/upload/ is up and running, but for some reason, connection timed out. Try again?
```

I check with `curl` and web, no problem.
```
 curl -v 172.19.0.3:8001/upload/
* Hostname was NOT found in DNS cache
*   Trying 172.19.0.3...
* Connected to 172.19.0.3 (172.19.0.3) port 8001 (#0)
> GET /upload/ HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 172.19.0.3:8001
> Accept: */*
> 
< HTTP/1.1 200 OK
* Server nginx/1.10.2 is not blacklisted
< Server: nginx/1.10.2
< Date: Tue, 01 Aug 2017 07:32:21 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 7049
< Connection: keep-alive
< Set-Cookie: session=86801d35-d82c-4ba7-8242-d5aeb1cbcfba.XG-kqXfC2a7clqWn_5Iq7_4Ys8E; HttpOnly; Path=/
< 
<!DOCTYPE HTML>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script type="text/javascript" src="/static/js/bootstrap.min.js"></script>
    <!-- <script src="//cdn.ckeditor.com/4.4.5/standard/ckeditor.js"></script> -->
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.css" media="screen" />
    <link rel="stylesheet/less" type="text/css" href="/static/css/bootswatch.less" media="screen" />
    <link rel="stylesheet/less" type="text/css" href="/static/css/variables.less" media="screen" />
    <link href="/static/css/bootstrap-responsive.css" rel="stylesheet">
    <!-- <link rel="stylesheet" type="text/css" href="/static/css/fileinput.css" media="screen" /> -->
```

**Comment by arcolife** [comment]
Hi, thanks for opening this issue. Sarjitsu services could be access through nginx container's address, not through backend contaner. I've just updated the essentials at https://github.com/arcolife/sarjitsu#usage. Please refer to that and to sample vizit config, as under https://github.com/arcolife/sarjitsu/blob/master/utils/conf/vizit.cfg#L7

thanks!
