### ISSUE TITLE
Grafana - CPU UTILIZATION [ALL] Graph is not show

### ISSUE THREAD

**Issue by lubry** [arcolife/sarjitsu#11]
In my sarjitsu_frontend (grafana)  CPU Utilization [ALL] Graph is not show. I am generate sar file from sosreport with command `$ sudo sosreport`
Any solution?
Thanks.

Screenshoot Grafana: 
[![SPost-creenshot_at_2017-08-03_09_43_15.png](https://s3.postimg.org/qhg4jdbr7/SPost-creenshot_at_2017-08-03_09_43_15.png)](https://postimg.org/image/efkqp82in/)
[![def2_Screenshot_at_2017-08-03_09_46_11.png](https://s4.postimg.org/kvy715e71/def2_Screenshot_at_2017-08-03_09_46_11.png)](https://postimg.org/image/xncd7nnyx/)

Other method using showing CPU Utilization using ksar.
[![CPUScreenshot_at_2017-08-03_10_18_48.png](https://s2.postimg.org/82ecdovc9/CPUScreenshot_at_2017-08-03_10_18_48.png)](https://postimg.org/image/nb49rgp0l/)

**Comment by arcolife** [comment]
so, please go through the following references:
- https://github.com/arcolife/sarjitsu#upcoming-features
- https://github.com/distributed-system-analysis/sarjitsu/issues/16
- https://github.com/grafana/grafana/pull/4694 
- https://github.com/grafana/grafana/pull/7863#issuecomment-315438252

there was a huge effort around this that's been waiting on grafana's maintainer to merge/review the code. 
This is out of sarjitsu's scope. 

what one could do instead, is work on https://github.com/distributed-system-analysis/sarjitsu/issues/12

**Comment by lubry** [comment]
thanks for inform @arcolife
