### ISSUE TITLE
Merge binary sar files not show in sarjitsu_frontend (Grafana) 

### ISSUE THREAD

**Issue by lubry** [arcolife/sarjitsu#12]
I have many binary sar files, Ii merge with command `# cat sa01 sa02 sa03 > merge_sa` then I upload using Sarjitsu Web Upload, but graph just show first time, I hope can show all the time in merge binary, any solution? Thanks.

**Comment by arcolife** [comment]
Hey that's not what sarjitsu supports. it works on binary, assuming the file is 1 single day's worth of data. 
Also, the whole logic of sarjitsu works on the fact that it uses header info/bytes from the binary to recognize the version of SA binary it belongs to and subsequently, the OS that it was generated from.
Combining 3 files into 1 means, logic failure on this part.

Do you have an idea of how to deal with this elegantly? I would rather upload them in parallel with post requests, than combine all in 1.

**Comment by lubry** [comment]
I am usualy convert binary to text and I merge using direct merge `cat`. It just can merge in same month, if diferent month, I merge same month to get 1 file text and merge other months to get 1 text. Then I merge 2 file different  month, thats work.

**Comment by arcolife** [comment]
I didn't get that. could you explain with an example of month wise SA files? also, sarjitsu only takes in binaries, not text..

**Comment by lubry** [comment]
Sure, sarjitsu just use binary not text. it is just different method for sar procesing. I usualy generate 1 sar file, 1 day. The problem when I generate sar in mid-month so i must merge in same month then merge in different month.

This example:
[![CPUScreenshot_at_2017-08-04_09_32_48.png](https://s20.postimg.org/wj8ywpg7h/CPUScreenshot_at_2017-08-04_09_32_48.png)](https://postimg.org/image/58nnosdah/)

**Comment by arcolife** [comment]
Why do you need to merge SA binaries? is that something ksar supports? 
 
Are you saying you'd like sarjitsu to process merged binaries?

**Comment by lubry** [comment]
I think many people need to merge graph. example use: for monthly report, yearly report or other uses. 
No kSar not support merge binary, kSar just view graph from text not binary.

Yes, if merge binary is possible. Other option is: merge in graph, not in binary merges, but merged in elasticsearch or postgresql before graph display.

**Comment by arcolife** [comment]
@lubry hey thanks for the suggestion. It could be added as a functionality, but really we'd have to decide on a max size limit of those blobs.

Currently multi day/month data could be viewed by uploading all files and then expanding time range in Grafana to a month or as per the need. Is that something you've tried yet? 

Also, you're welcome to start a discussion around this on a new google group I've just created. Here: https://groups.google.com/forum/#!forum/sarjitsu

thanks!

**Comment by lubry** [comment]
Yes thanks, I think the problem is solved, but grafana dashboard is many list binary. Sure I will join. I want to discuss to improve sarjitsu too. Thanks very much @arcolife

**Comment by arcolife** [comment]
thanks @lubry ! Hope to see an email from you soon :-) 

I think the issues to be discussed would include:
1. either have single dashboard selection feature for multi file upload of same server kind (avoid per day multiple dashboards)
2. have single upload (merged) of multiple binary files.

SA binary is something we'd like to upload, and not SAR text, because SAR extracted data is much bigger as compared to binaries. 

Also, I'm personally in favor of option 1, because that should be a visualization feature frankly, rather than enforcing it on backend logic. The only thing then left, would be to have sarjitsu identify consecutive (or atleast in a month's range) of same node's binary files.

**Comment by lubry** [comment]
Thanks @arcolife 
I've joined in the discussion of google group, waiting for your approval for join
