### ISSUE TITLE
Web Backend Not working

### ISSUE THREAD

**Issue by gizlonk** [arcolife/sarjitsu#7]
Hi, I'm new to docker and all that, but have been asked to check this out for our reporting needs.

I installed docker and the containers, and started them up. I can access graphana, but not the "backend" on port 9704. 

[root@krokodil sarjitsu]# curl http://localhost:9701
{
  "status" : 200,
  "name" : "Uatu",
  "cluster_name" : "elasticsearch9886",
  "version" : {
    "number" : "1.7.3",
    "build_hash" : "05d4530971ef0ea46d0f4fa6ee64dbc8df659682",
    "build_timestamp" : "2015-10-15T09:14:17Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
[root@krokodil sarjitsu]# curl http://localhost:9702
<a href="/login">Found</a>.

[root@krokodil sarjitsu]# curl http://localhost:9703
{
  "api_test": "OK"
}[root@krokodil sarjitsu]# curl http://localhost:9704
curl: (56) Recv failure: Connection reset by peer

I am not sure how to troubleshoot this. Any help will be awesome. Thanks.

**Comment by gizlonk** [comment]
docker logs:

[uWSGI] getting INI configuration from /opt/sarjitsu/conf/sarjitsu.ini
*** Starting uWSGI 2.0.15 (64bit) on [Tue Jun 27 07:01:43 2017] ***
compiled with version: 5.3.1 20160406 (Red Hat 5.3.1-6) on 15 June 2017 10:58:00
os: Linux-4.11.4-100.fc24.x86_64 #1 SMP Wed Jun 7 20:06:39 UTC 2017
nodename: 535df5434f3f
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /opt/sarjitsu/src
detected binary path: /usr/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /opt/sarjitsu/src/
your processes number limit is 1048576
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.4.3 (default, Aug  9 2016, 15:36:17)  [GCC 5.3.1 20160406 (Red Hat 5.3.1-6)]
Python main interpreter initialized at 0x2438a60
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 436560 bytes (426 KB) for 5 cores
*** Operational MODE: preforking ***
added /usr/bin/python3 to pythonpath.
/usr/lib/python3.4/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.12) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "./wsgi.py", line 1, in <module>
    from server import app as application
  File "./server.py", line 5, in <module>
    import requests
  File "/usr/lib/python3.4/site-packages/requests/__init__.py", line 90, in <module>
    from urllib3.exceptions import DependencyWarning
ImportError: cannot import name 'DependencyWarning'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 17)
spawned uWSGI worker 1 (pid: 19, cores: 1)
spawned uWSGI worker 2 (pid: 20, cores: 1)
spawned uWSGI worker 3 (pid: 21, cores: 1)
spawned uWSGI worker 4 (pid: 22, cores: 1)
spawned uWSGI worker 5 (pid: 23, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 21|app: -1|req: -1/1] 172.18.0.1 () {42 vars in 795 bytes} [Tue Jun 27 07:12:36 2017] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 21|app: -1|req: -1/2] 172.18.0.1 () {42 vars in 774 bytes} [Tue Jun 27 07:12:36 2017] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
[uWSGI] getting INI configuration from /opt/sarjitsu/conf/sarjitsu.ini
*** Starting uWSGI 2.0.15 (64bit) on [Tue Jun 27 07:24:37 2017] ***
compiled with version: 5.3.1 20160406 (Red Hat 5.3.1-6) on 15 June 2017 10:58:00
os: Linux-4.11.4-100.fc24.x86_64 #1 SMP Wed Jun 7 20:06:39 UTC 2017
nodename: 535df5434f3f
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /opt/sarjitsu/src
detected binary path: /usr/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /opt/sarjitsu/src/
your processes number limit is 1048576
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.4.3 (default, Aug  9 2016, 15:36:17)  [GCC 5.3.1 20160406 (Red Hat 5.3.1-6)]
Python main interpreter initialized at 0x127da60
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 436560 bytes (426 KB) for 5 cores
*** Operational MODE: preforking ***
added /usr/bin/python3 to pythonpath.
/usr/lib/python3.4/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.12) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "./wsgi.py", line 1, in <module>
    from server import app as application
  File "./server.py", line 5, in <module>
    import requests
  File "/usr/lib/python3.4/site-packages/requests/__init__.py", line 90, in <module>
    from urllib3.exceptions import DependencyWarning
ImportError: cannot import name 'DependencyWarning'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 18)
spawned uWSGI worker 1 (pid: 20, cores: 1)
spawned uWSGI worker 2 (pid: 21, cores: 1)
spawned uWSGI worker 3 (pid: 22, cores: 1)
spawned uWSGI worker 4 (pid: 23, cores: 1)
spawned uWSGI worker 5 (pid: 24, cores: 1)
[uWSGI] getting INI configuration from /opt/sarjitsu/conf/sarjitsu.ini
*** Starting uWSGI 2.0.15 (64bit) on [Tue Jun 27 08:14:54 2017] ***
compiled with version: 5.3.1 20160406 (Red Hat 5.3.1-6) on 15 June 2017 10:58:00
os: Linux-4.11.4-100.fc24.x86_64 #1 SMP Wed Jun 7 20:06:39 UTC 2017
nodename: 535df5434f3f
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /opt/sarjitsu/src
detected binary path: /usr/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /opt/sarjitsu/src/
your processes number limit is 1048576
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.4.3 (default, Aug  9 2016, 15:36:17)  [GCC 5.3.1 20160406 (Red Hat 5.3.1-6)]
Python main interpreter initialized at 0xe38a60
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 436560 bytes (426 KB) for 5 cores
*** Operational MODE: preforking ***
added /usr/bin/python3 to pythonpath.
/usr/lib/python3.4/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.12) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "./wsgi.py", line 1, in <module>
    from server import app as application
  File "./server.py", line 5, in <module>
    import requests
  File "/usr/lib/python3.4/site-packages/requests/__init__.py", line 90, in <module>
    from urllib3.exceptions import DependencyWarning
ImportError: cannot import name 'DependencyWarning'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 17)
spawned uWSGI worker 1 (pid: 19, cores: 1)
spawned uWSGI worker 2 (pid: 20, cores: 1)
spawned uWSGI worker 3 (pid: 21, cores: 1)
spawned uWSGI worker 4 (pid: 22, cores: 1)
spawned uWSGI worker 5 (pid: 23, cores: 1)
[uWSGI] getting INI configuration from /opt/sarjitsu/conf/sarjitsu.ini
*** Starting uWSGI 2.0.15 (64bit) on [Tue Jun 27 08:21:16 2017] ***
compiled with version: 5.3.1 20160406 (Red Hat 5.3.1-6) on 15 June 2017 10:58:00
os: Linux-4.11.4-100.fc24.x86_64 #1 SMP Wed Jun 7 20:06:39 UTC 2017
nodename: 535df5434f3f
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /opt/sarjitsu/src
detected binary path: /usr/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /opt/sarjitsu/src/
your processes number limit is 1048576
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.4.3 (default, Aug  9 2016, 15:36:17)  [GCC 5.3.1 20160406 (Red Hat 5.3.1-6)]
Python main interpreter initialized at 0x14d0a60
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 436560 bytes (426 KB) for 5 cores
*** Operational MODE: preforking ***
added /usr/bin/python3 to pythonpath.
/usr/lib/python3.4/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.12) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "./wsgi.py", line 1, in <module>
    from server import app as application
  File "./server.py", line 5, in <module>
    import requests
  File "/usr/lib/python3.4/site-packages/requests/__init__.py", line 90, in <module>
    from urllib3.exceptions import DependencyWarning
ImportError: cannot import name 'DependencyWarning'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 17)
spawned uWSGI worker 1 (pid: 19, cores: 1)
spawned uWSGI worker 2 (pid: 20, cores: 1)
spawned uWSGI worker 3 (pid: 21, cores: 1)
spawned uWSGI worker 4 (pid: 22, cores: 1)
spawned uWSGI worker 5 (pid: 23, cores: 1)

**Comment by arcolife** [comment]
for context, reason this issue was closed was another one https://github.com/arcolife/sarjitsu/issues/8 

@gizlonk hey you could've edited your issue with the docker logs in same comment (or separate works too; assuming that's the reason you closed this one). 

But that's okay since you've opened another one now..
