### ISSUE TITLE
Web Backend not Working

### ISSUE THREAD

**Issue by gizlonk** [arcolife/sarjitsu#8]
Hi, I'm new to docker and all that, but have been asked to check this out for our reporting needs.

I installed docker and the containers, and started them up. I can access graphana, but not the "backend" on port 9704.

[root@krokodil sarjitsu]# curl http://localhost:9701
{
"status" : 200,
"name" : "Uatu",
"cluster_name" : "elasticsearch9886",
"version" : {
"number" : "1.7.3",
"build_hash" : "05d4530971ef0ea46d0f4fa6ee64dbc8df659682",
"build_timestamp" : "2015-10-15T09:14:17Z",
"build_snapshot" : false,
"lucene_version" : "4.10.4"
},
"tagline" : "You Know, for Search"
}
[root@krokodil sarjitsu]# curl http://localhost:9702
Found.

[root@krokodil sarjitsu]# curl http://localhost:9703
{
"api_test": "OK"
}[root@krokodil sarjitsu]# curl http://localhost:9704
curl: (56) Recv failure: Connection reset by peer

docker logs:

[uWSGI] getting INI configuration from /opt/sarjitsu/conf/sarjitsu.ini
*** Starting uWSGI 2.0.15 (64bit) on [Tue Jun 27 07:01:43 2017] ***
compiled with version: 5.3.1 20160406 (Red Hat 5.3.1-6) on 15 June 2017 10:58:00
os: Linux-4.11.4-100.fc24.x86_64 #1 SMP Wed Jun 7 20:06:39 UTC 2017
nodename: 535df5434f3f
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /opt/sarjitsu/src
detected binary path: /usr/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /opt/sarjitsu/src/
your processes number limit is 1048576
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
Python version: 3.4.3 (default, Aug 9 2016, 15:36:17) [GCC 5.3.1 20160406 (Red Hat 5.3.1-6)]
Python main interpreter initialized at 0x2438a60
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 436560 bytes (426 KB) for 5 cores
*** Operational MODE: preforking ***
added /usr/bin/python3 to pythonpath.
/usr/lib/python3.4/site-packages/requests/init.py:80: RequestsDependencyWarning: urllib3 (1.12) or chardet (3.0.4) doesn't match a supported version!
RequestsDependencyWarning)
Traceback (most recent call last):
File "./wsgi.py", line 1, in 
from server import app as application
File "./server.py", line 5, in 
import requests
File "/usr/lib/python3.4/site-packages/requests/init.py", line 90, in 
from urllib3.exceptions import DependencyWarning
ImportError: cannot import name 'DependencyWarning'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 17)
spawned uWSGI worker 1 (pid: 19, cores: 1)
spawned uWSGI worker 2 (pid: 20, cores: 1)
spawned uWSGI worker 3 (pid: 21, cores: 1)
spawned uWSGI worker 4 (pid: 22, cores: 1)
spawned uWSGI worker 5 (pid: 23, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 21|app: -1|req: -1/1] 172.18.0.1 () {42 vars in 795 bytes} [Tue Jun 27 07:12:36 2017] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 21|app: -1|req: -1/2] 172.18.0.1 () {42 vars in 774 bytes} [Tue Jun 27 07:12:36 2017] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
[uWSGI] getting INI configuration from /opt/sarjitsu/conf/sarjitsu.ini
*** Starting uWSGI 2.0.15 (64bit) on [Tue Jun 27 07:24:37 2017] ***
compiled with version: 5.3.1 20160406 (Red Hat 5.3.1-6) on 15 June 2017 10:58:00
os: Linux-4.11.4-100.fc24.x86_64 #1 SMP Wed Jun 7 20:06:39 UTC 2017
nodename: 535df5434f3f
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /opt/sarjitsu/src
detected binary path: /usr/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /opt/sarjitsu/src/
your processes number limit is 1048576
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
Python version: 3.4.3 (default, Aug 9 2016, 15:36:17) [GCC 5.3.1 20160406 (Red Hat 5.3.1-6)]
Python main interpreter initialized at 0x127da60
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 436560 bytes (426 KB) for 5 cores
*** Operational MODE: preforking ***
added /usr/bin/python3 to pythonpath.
/usr/lib/python3.4/site-packages/requests/init.py:80: RequestsDependencyWarning: urllib3 (1.12) or chardet (3.0.4) doesn't match a supported version!
RequestsDependencyWarning)
Traceback (most recent call last):
File "./wsgi.py", line 1, in 
from server import app as application
File "./server.py", line 5, in 
import requests
File "/usr/lib/python3.4/site-packages/requests/init.py", line 90, in 
from urllib3.exceptions import DependencyWarning
ImportError: cannot import name 'DependencyWarning'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 18)
spawned uWSGI worker 1 (pid: 20, cores: 1)
spawned uWSGI worker 2 (pid: 21, cores: 1)
spawned uWSGI worker 3 (pid: 22, cores: 1)
spawned uWSGI worker 4 (pid: 23, cores: 1)
spawned uWSGI worker 5 (pid: 24, cores: 1)
[uWSGI] getting INI configuration from /opt/sarjitsu/conf/sarjitsu.ini
*** Starting uWSGI 2.0.15 (64bit) on [Tue Jun 27 08:14:54 2017] ***
compiled with version: 5.3.1 20160406 (Red Hat 5.3.1-6) on 15 June 2017 10:58:00
os: Linux-4.11.4-100.fc24.x86_64 #1 SMP Wed Jun 7 20:06:39 UTC 2017
nodename: 535df5434f3f
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /opt/sarjitsu/src
detected binary path: /usr/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /opt/sarjitsu/src/
your processes number limit is 1048576
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
Python version: 3.4.3 (default, Aug 9 2016, 15:36:17) [GCC 5.3.1 20160406 (Red Hat 5.3.1-6)]
Python main interpreter initialized at 0xe38a60
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 436560 bytes (426 KB) for 5 cores
*** Operational MODE: preforking ***
added /usr/bin/python3 to pythonpath.
/usr/lib/python3.4/site-packages/requests/init.py:80: RequestsDependencyWarning: urllib3 (1.12) or chardet (3.0.4) doesn't match a supported version!
RequestsDependencyWarning)
Traceback (most recent call last):
File "./wsgi.py", line 1, in 
from server import app as application
File "./server.py", line 5, in 
import requests
File "/usr/lib/python3.4/site-packages/requests/init.py", line 90, in 
from urllib3.exceptions import DependencyWarning
ImportError: cannot import name 'DependencyWarning'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 17)
spawned uWSGI worker 1 (pid: 19, cores: 1)
spawned uWSGI worker 2 (pid: 20, cores: 1)
spawned uWSGI worker 3 (pid: 21, cores: 1)
spawned uWSGI worker 4 (pid: 22, cores: 1)
spawned uWSGI worker 5 (pid: 23, cores: 1)
[uWSGI] getting INI configuration from /opt/sarjitsu/conf/sarjitsu.ini
*** Starting uWSGI 2.0.15 (64bit) on [Tue Jun 27 08:21:16 2017] ***
compiled with version: 5.3.1 20160406 (Red Hat 5.3.1-6) on 15 June 2017 10:58:00
os: Linux-4.11.4-100.fc24.x86_64 #1 SMP Wed Jun 7 20:06:39 UTC 2017
nodename: 535df5434f3f
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /opt/sarjitsu/src
detected binary path: /usr/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /opt/sarjitsu/src/
your processes number limit is 1048576
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
Python version: 3.4.3 (default, Aug 9 2016, 15:36:17) [GCC 5.3.1 20160406 (Red Hat 5.3.1-6)]
Python main interpreter initialized at 0x14d0a60
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 436560 bytes (426 KB) for 5 cores
*** Operational MODE: preforking ***
added /usr/bin/python3 to pythonpath.
/usr/lib/python3.4/site-packages/requests/init.py:80: RequestsDependencyWarning: urllib3 (1.12) or chardet (3.0.4) doesn't match a supported version!
RequestsDependencyWarning)
Traceback (most recent call last):
File "./wsgi.py", line 1, in 
from server import app as application
File "./server.py", line 5, in 
import requests
File "/usr/lib/python3.4/site-packages/requests/init.py", line 90, in 
from urllib3.exceptions import DependencyWarning
ImportError: cannot import name 'DependencyWarning'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 17)
spawned uWSGI worker 1 (pid: 19, cores: 1)
spawned uWSGI worker 2 (pid: 20, cores: 1)
spawned uWSGI worker 3 (pid: 21, cores: 1)
spawned uWSGI worker 4 (pid: 22, cores: 1)
spawned uWSGI worker 5 (pid: 23, cores: 1)

I am not sure how to troubleshoot this. Any help will be awesome. Thanks.

**Comment by arcolife** [comment]
Hi @gizlonk This looks like a python pip's dependency issue with the 'requests' module.

See this line in your traceback from backend's log:
```
Traceback (most recent call last):
File "./wsgi.py", line 1, in
from server import app as application
File "./server.py", line 5, in
import requests
File "/usr/lib/python3.4/site-packages/requests/init.py", line 90, in
from urllib3.exceptions import DependencyWarning
ImportError: cannot import name 'DependencyWarning'
unable to load app 0 (mountpoint='') (callable not found or import error)
```

I'm not sure why it's creeping in with the version that I mention in https://github.com/arcolife/sarjitsu/blob/master/lib/backend/src/requirements.txt#L12 which gets built into the docker image during https://github.com/arcolife/sarjitsu/blob/master/lib/backend/Dockerfile#L26

Refer to this link for temporary fix:
https://github.com/nickoala/telepot/issues/80#issuecomment-219019007

To apply the fix, run `$ docker-compose exec web bash` (I think that's the command to login to `backend`) and then repeat the steps in the fix. 

Meanwhile, I'll debug this later myself. Thanks for opening an issue.

**Comment by arcolife** [comment]
FWIW this seems to be related to changes I made for  https://github.com/arcolife/sarjitsu/issues/5#issuecomment-305507297 (changes: https://github.com/arcolife/sarjitsu/commit/f6b637cc5ad66a9f2ab3ddc2b624c88d9a104a6e#diff-995e04481dfca0d5a77bd2d19ffc2203 )

**Comment by gizlonk** [comment]
@arcolife - forgive me if im being an idiot.

On the link you posted, the solution is to reinstall requests via pip - i have done this, without any effect. I cannot run it inside the container as there is no pip installed. What am I doing wrong?

**Comment by arcolife** [comment]
@gizlonk hehe. so where have you done reinstallation through pip if you say pip isn't installed inside container? 

Also, is the web container still running? if so, `pip` should be disguised as `pip3`. See again https://github.com/arcolife/sarjitsu/blob/master/lib/backend/Dockerfile#L26

**Comment by arcolife** [comment]
and so, if after reinstallation through pip, it doesn't improve, try upgrading the version in your requirements.txt's copy of the repo under https://github.com/arcolife/sarjitsu/blob/master/lib/backend/src/requirements.txt#L12 and then rebuild the image with `docker-compose build .`

change it to 2.18.1. Let me know if that works well. If it works, please send a PR :-)

**Comment by gizlonk** [comment]
I was running the pip install on my laptop, not inside the container. 

Thank you, i tried pip3 inside the container and that worked. Still no joy, however.

I then updated my requirements.txt as you said, and ran `docker-compose build`, but still get the same result. Logs have changed, however. 

If you can, please have a look at https://pastebin.com/hjzSA4P3 - once i get this running, with your permission, i think id like to write up a how to for noobs. like me.

**Comment by arcolife** [comment]
I just checked locally and it's an issue with urllib's version while this python statement `from urllib3.exceptions import DependencyWarning` gets executed in `requests`'s `__init__.py`. 
So to speak, you'd wanna change requests to 2.18.1 as well as `urllib3==1.12` to `urllib3==1.21.1`

Also this time, `docker-compose build .`, do a `docker-compose up --build -d`. I think your containers might not have been recreated with that former command.

**Comment by gizlonk** [comment]
Any chance of reopening this? Apologies for the tardy reply - emergency at work prevented me from continuing. I have made the suggested changes, but still no joy.

**Comment by arcolife** [comment]
@gizlonk Hi, I deleted all my images locally and built them from ground up again with the master branch commits and it works! (I hope I've fixed that issue in https://github.com/arcolife/sarjitsu/commit/ef2762071588ef8b44b8f6017cd71998accdebdc#diff-995e04481dfca0d5a77bd2d19ffc2203 )

Could you pull in the latest master branch code and try this again?

**Comment by gizlonk** [comment]
@arcolife did you use the updated requirements? Or should i just clone and rebuild everything?

**Comment by arcolife** [comment]
yes i used updated requirements to rebuild. You could just pull in the latest code and docker would detect changes in codebase for backend and rebuild from there if you supply `docker-compose up --build -d`. Also, kill and remove any old running containers before this. 

But if you think there's an issue with merger of your current HEAD branch with master of this repo, then that's a different issue.

**Comment by arcolife** [comment]
also ports mappings have changed. please copy env.example to .env again after you pull in latest 
ref: https://github.com/arcolife/sarjitsu/blob/master/env.example#L25

**Comment by gizlonk** [comment]
@arcolife awesome - i pulled it all in again, and everything is running, BUT, not working.

What I mean by that is I uploaded a sar file to the backend, and it gave me the URL for grafana, but the dash is not populated. Do i need to manually create the dash?

Again, thanks for your help on this.

**Comment by arcolife** [comment]
oh that's weird. Did you click on list of dashboard dropdown to see if any were formed? it's something with grafana UI. doesn't show new ones created on homepage. There's a top left corner dropdown list to see those..

**Comment by arcolife** [comment]
also, did you click 'check_all' while uploading the file? sarjitsu currently only supports that version. Sorry about the slack, but it's a side project :-) I'll spend time whenever I can, otherwise I'd welcome you to send a PR for that. Alas, this is me digressing on this thread.

**Comment by gizlonk** [comment]
Under "dashboards" i have home, playlists and snapshots, nothing else. 

I did try the check_all and it does not create a dash. I also tried manipulating the time period (my initial test sa was sa29, from last month, although the same thing happens with sa01)

Thank you for all your help so far!

**Comment by arcolife** [comment]
Time period is auto selected by the framework so that shouldn't be the concern! Could you perhaps forward me your sa01 and sa29 in that email thread?
 
Btw, when you DO manage to get the dashboard, you wouldn't see data for CPU, network and disk. 

references: 
- https://github.com/distributed-system-analysis/sarjitsu/issues/16
- https://github.com/distributed-system-analysis/sarjitsu/issues/12

You're actually spending time on this and it makes me wanna contribute more time to this repo. Thanks!

**Comment by gizlonk** [comment]
Sent you the sa files.

**Comment by arcolife** [comment]
For public reference, those 2 worked on my side. I'd rather look at your docker-compose logs now..

![screenshot from 2017-07-03 17-26-22](https://user-images.githubusercontent.com/920859/27792029-6fd25276-6015-11e7-84e8-8f80a91c9a0b.png)

![screenshot from 2017-07-03 17-25-05](https://user-images.githubusercontent.com/920859/27792009-58f5b5f2-6015-11e7-88c9-2f37573e9b64.png)
